//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormationInfo
    {
        public int FormationInfoId { get; set; }
        public int GameID { get; set; }
        public int TeamID { get; set; }
        public string TeamNameS { get; set; }
        public int FormationID { get; set; }
        public string FormationName { get; set; }
        public int PlayerID { get; set; }
        public string PlayerName { get; set; }
        public string PlayerUniformNo { get; set; }
        public string PlayerPosition { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
