//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameStateLG
    {
        public int GameStateLGId { get; set; }
        public int TeamInfoLGId { get; set; }
        public int ID { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> PK { get; set; }
        public Nullable<int> GK { get; set; }
        public Nullable<int> Shoot { get; set; }
        public Nullable<int> FK { get; set; }
        public Nullable<int> Yellow { get; set; }
        public Nullable<int> Red { get; set; }
        public Nullable<int> CK { get; set; }
        public Nullable<int> ShootGoal { get; set; }
        public Nullable<int> Offside { get; set; }
        public Nullable<int> Gain { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
