//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameEndInfoLG
    {
        public int GameEndInfoLGId { get; set; }
        public int GameReportLGId { get; set; }
        public string Condition { get; set; }
        public string Surface { get; set; }
        public string Weather { get; set; }
        public string Wind { get; set; }
        public string Temperature { get; set; }
        public Nullable<int> Spectators { get; set; }
        public Nullable<int> Humidity { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
