//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoalInfoLG
    {
        public int GoalInfoLGId { get; set; }
        public int GameReportLGId { get; set; }
        public int No { get; set; }
        public int StateID { get; set; }
        public string StateName { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<int> Half { get; set; }
        public Nullable<int> TeamID { get; set; }
        public string TeamNameS { get; set; }
        public Nullable<int> GPlayerID { get; set; }
        public string GPlayerName { get; set; }
        public string GPlayerNameS { get; set; }
        public string GPlayerUni { get; set; }
        public string Body { get; set; }
        public string Operation { get; set; }
        public Nullable<int> APlayerID { get; set; }
        public string APlayerName { get; set; }
        public string APlayerNameS { get; set; }
        public string APlayerUni { get; set; }
        public string AssistKind { get; set; }
        public Nullable<short> OwnGoalF { get; set; }
        public Nullable<int> ScoreTeamID { get; set; }
        public string ScoreTeamNameS { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
