//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JlgEntities : DbContext
    {
        public JlgEntities()
            : base("name=JlgEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BenchInfoLP> BenchInfoLP { get; set; }
        public virtual DbSet<CategoryGT> CategoryGT { get; set; }
        public virtual DbSet<ChangeInfoLP> ChangeInfoLP { get; set; }
        public virtual DbSet<CommentInfo> CommentInfo { get; set; }
        public virtual DbSet<CommentReport> CommentReport { get; set; }
        public virtual DbSet<DirectoryDA> DirectoryDA { get; set; }
        public virtual DbSet<DirectoryDI> DirectoryDI { get; set; }
        public virtual DbSet<GainInfoLG> GainInfoLG { get; set; }
        public virtual DbSet<GameCategory> GameCategory { get; set; }
        public virtual DbSet<GameCategoryHE> GameCategoryHE { get; set; }
        public virtual DbSet<GameCategoryMR> GameCategoryMR { get; set; }
        public virtual DbSet<GameEndInfoLG> GameEndInfoLG { get; set; }
        public virtual DbSet<GameInfoMR> GameInfoMR { get; set; }
        public virtual DbSet<GameKindInfo> GameKindInfo { get; set; }
        public virtual DbSet<GameKindMST> GameKindMST { get; set; }
        public virtual DbSet<GameKindTeamGT> GameKindTeamGT { get; set; }
        public virtual DbSet<GameReportLG> GameReportLG { get; set; }
        public virtual DbSet<GameSchedule> GameSchedule { get; set; }
        public virtual DbSet<GameStateLG> GameStateLG { get; set; }
        public virtual DbSet<GoalInfoLG> GoalInfoLG { get; set; }
        public virtual DbSet<LeagueInfo> LeagueInfo { get; set; }
        public virtual DbSet<LeagueMST> LeagueMST { get; set; }
        public virtual DbSet<MasterTransfersJlg> MasterTransfersJlg { get; set; }
        public virtual DbSet<NowOrderInfoLP> NowOrderInfoLP { get; set; }
        public virtual DbSet<PKInfoLG> PKInfoLG { get; set; }
        public virtual DbSet<PlayerInfoDA> PlayerInfoDA { get; set; }
        public virtual DbSet<PlayerInfoDI> PlayerInfoDI { get; set; }
        public virtual DbSet<PlayerInfoLPBE> PlayerInfoLPBE { get; set; }
        public virtual DbSet<PlayerInfoLPCH> PlayerInfoLPCH { get; set; }
        public virtual DbSet<PlayerInfoLPNO> PlayerInfoLPNO { get; set; }
        public virtual DbSet<PlayerInfoLPST> PlayerInfoLPST { get; set; }
        public virtual DbSet<PlayerInfoPL> PlayerInfoPL { get; set; }
        public virtual DbSet<PlayerInfoPS> PlayerInfoPS { get; set; }
        public virtual DbSet<PlayerInfoRE> PlayerInfoRE { get; set; }
        public virtual DbSet<PlayerLG> PlayerLG { get; set; }
        public virtual DbSet<PlayerMSTPL> PlayerMSTPL { get; set; }
        public virtual DbSet<PlayerReportLP> PlayerReportLP { get; set; }
        public virtual DbSet<PlayerStatsReportPS> PlayerStatsReportPS { get; set; }
        public virtual DbSet<RankGoalReportRG> RankGoalReportRG { get; set; }
        public virtual DbSet<RankInfoRG> RankInfoRG { get; set; }
        public virtual DbSet<RankInfoRT> RankInfoRT { get; set; }
        public virtual DbSet<RankReportRT> RankReportRT { get; set; }
        public virtual DbSet<RecapReportRE> RecapReportRE { get; set; }
        public virtual DbSet<ResultInfoHE> ResultInfoHE { get; set; }
        public virtual DbSet<ResultInfoSS> ResultInfoSS { get; set; }
        public virtual DbSet<ResultInfoT5> ResultInfoT5 { get; set; }
        public virtual DbSet<ResultInfoTC> ResultInfoTC { get; set; }
        public virtual DbSet<ScheduleInfo> ScheduleInfo { get; set; }
        public virtual DbSet<ScheduleInfoHE> ScheduleInfoHE { get; set; }
        public virtual DbSet<ScorePlayerT5> ScorePlayerT5 { get; set; }
        public virtual DbSet<SeasonInfo> SeasonInfo { get; set; }
        public virtual DbSet<SeasonMST> SeasonMST { get; set; }
        public virtual DbSet<SecGameRecordReportMR> SecGameRecordReportMR { get; set; }
        public virtual DbSet<StartingInfoLP> StartingInfoLP { get; set; }
        public virtual DbSet<Team5thGameReportT5> Team5thGameReportT5 { get; set; }
        public virtual DbSet<TeamCardReportTC> TeamCardReportTC { get; set; }
        public virtual DbSet<TeamInfoGT> TeamInfoGT { get; set; }
        public virtual DbSet<TeamInfoLG> TeamInfoLG { get; set; }
        public virtual DbSet<TeamInfoRE> TeamInfoRE { get; set; }
        public virtual DbSet<TeamInfoTC> TeamInfoTC { get; set; }
        public virtual DbSet<TeamInfoTE> TeamInfoTE { get; set; }
        public virtual DbSet<TeamInfoTS> TeamInfoTS { get; set; }
        public virtual DbSet<TeamMSTTE> TeamMSTTE { get; set; }
        public virtual DbSet<TeamScheduleReportHE> TeamScheduleReportHE { get; set; }
        public virtual DbSet<TeamSeasonReportSS> TeamSeasonReportSS { get; set; }
        public virtual DbSet<TeamStatsReportTS> TeamStatsReportTS { get; set; }
        public virtual DbSet<TimeInfoLG> TimeInfoLG { get; set; }
        public virtual DbSet<WarningInfoLG> WarningInfoLG { get; set; }
        public virtual DbSet<TeamIconJlg> TeamIconJlg { get; set; }
        public virtual DbSet<PlayerLS> PlayerLS { get; set; }
        public virtual DbSet<StatsReportLS> StatsReportLS { get; set; }
        public virtual DbSet<TeamInfoLS> TeamInfoLS { get; set; }
        public virtual DbSet<FormationInfo> FormationInfo { get; set; }
        public virtual DbSet<FormationReportLF> FormationReportLF { get; set; }
        public virtual DbSet<GameInfoSR> GameInfoSR { get; set; }
        public virtual DbSet<InjulyReportIR> InjulyReportIR { get; set; }
        public virtual DbSet<PlayerCBP> PlayerCBP { get; set; }
        public virtual DbSet<PlayerInfoIR> PlayerInfoIR { get; set; }
        public virtual DbSet<PlayerInfoLF> PlayerInfoLF { get; set; }
        public virtual DbSet<ResultInfoTH> ResultInfoTH { get; set; }
        public virtual DbSet<ResultInfoTT> ResultInfoTT { get; set; }
        public virtual DbSet<SuspendReportSR> SuspendReportSR { get; set; }
        public virtual DbSet<SuspensionInfoSR> SuspensionInfoSR { get; set; }
        public virtual DbSet<TeamCBP> TeamCBP { get; set; }
        public virtual DbSet<TeamHAReportTH> TeamHAReportTH { get; set; }
        public virtual DbSet<TeamInfoIR> TeamInfoIR { get; set; }
        public virtual DbSet<TeamInfoLF> TeamInfoLF { get; set; }
        public virtual DbSet<TeamInfoTH> TeamInfoTH { get; set; }
        public virtual DbSet<TeamInfoTT> TeamInfoTT { get; set; }
        public virtual DbSet<TeamTimeReportTT> TeamTimeReportTT { get; set; }
        public virtual DbSet<TeamGameStats> TeamGameStats { get; set; }
        public virtual DbSet<TeamSeasonStats> TeamSeasonStats { get; set; }
    }
}
