//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeagueInfo
    {
        public int LeagueInfoId { get; set; }
        public int LeagueMSTId { get; set; }
        public int LeagueNo { get; set; }
        public int LeagueID { get; set; }
        public string LeagueName { get; set; }
        public string LeagueNameS { get; set; }
        public string LeagueNameE { get; set; }
        public string LeagueNameES { get; set; }
        public string NationalityNameS { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
