//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterTransfersJlg
    {
        public int Id { get; set; }
        public string No { get; set; }
        public string FunctionName { get; set; }
        public string FileName { get; set; }
        public string FilePathServer { get; set; }
        public string Schema { get; set; }
        public string SuffixTables { get; set; }
        public string IgnoreTables { get; set; }
        public string QuerySqlDelete { get; set; }
        public Nullable<short> HasCustomHeader { get; set; }
        public Nullable<short> HasSubFolder { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
