//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerInfoPL
    {
        public int PlayerInfoPLId { get; set; }
        public int PlayerMSTPLId { get; set; }
        public int PlayerNo { get; set; }
        public int PlayerID { get; set; }
        public string PlayerName { get; set; }
        public string PlayerNameS { get; set; }
        public string PlayerNameE { get; set; }
        public string PlayerNameES { get; set; }
        public string Position { get; set; }
        public string UniformNo { get; set; }
        public string NationalityName { get; set; }
        public string NationalityNameS { get; set; }
        public string NationalityNameE { get; set; }
        public string NationalityNameES { get; set; }
        public Nullable<int> RegisterF { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
