//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerCBP
    {
        public int GameKindID { get; set; }
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public int PlayerID { get; set; }
        public string PlayerName { get; set; }
        public string Position { get; set; }
        public int OfficialPlayingTime { get; set; }
        public int ActualPlayingTime { get; set; }
        public int PlayingGameCount { get; set; }
        public int StartingGameCount { get; set; }
        public double ShootCBP { get; set; }
        public double PassCBP { get; set; }
        public double CrossCBP { get; set; }
        public double DribbleCBP { get; set; }
        public double AttackCBP { get; set; }
        public double DefenseCBP { get; set; }
        public double SaveCBP { get; set; }
        public double ShootCBPAverage { get; set; }
        public double PassCBPAverage { get; set; }
        public double CrossCBPAverage { get; set; }
        public double DribbleCBPAverage { get; set; }
        public double AttackCBPAverage { get; set; }
        public double DefenseCBPAverage { get; set; }
        public double SaveCBPAverage { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
