//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerInfoLPCH
    {
        public int PlayerInfoLPCHId { get; set; }
        public int ChangeInfoLPId { get; set; }
        public int StateID { get; set; }
        public string StateName { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<int> Half { get; set; }
        public Nullable<short> ExitF { get; set; }
        public Nullable<int> InID { get; set; }
        public string InName { get; set; }
        public string InNameS { get; set; }
        public string InUni { get; set; }
        public string InPos { get; set; }
        public Nullable<int> OutID { get; set; }
        public string OutName { get; set; }
        public string OutNameS { get; set; }
        public string OutUni { get; set; }
        public string OutPos { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
