//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerInfoLF
    {
        public int PlayerInfoLFId { get; set; }
        public int TeamInfoLFId { get; set; }
        public int P1ID { get; set; }
        public string P1Name { get; set; }
        public string P1Uni { get; set; }
        public string P1Pos { get; set; }
        public int P1X { get; set; }
        public int P1Y { get; set; }
        public int P2ID { get; set; }
        public string P2Name { get; set; }
        public string P2Uni { get; set; }
        public string P2Pos { get; set; }
        public int P2X { get; set; }
        public int P2Y { get; set; }
        public int P3ID { get; set; }
        public string P3Name { get; set; }
        public string P3Uni { get; set; }
        public string P3Pos { get; set; }
        public int P3X { get; set; }
        public int P3Y { get; set; }
        public int P4ID { get; set; }
        public string P4Name { get; set; }
        public string P4Uni { get; set; }
        public string P4Pos { get; set; }
        public int P4X { get; set; }
        public int P4Y { get; set; }
        public int P5ID { get; set; }
        public string P5Name { get; set; }
        public string P5Uni { get; set; }
        public string P5Pos { get; set; }
        public int P5X { get; set; }
        public int P5Y { get; set; }
        public int P6ID { get; set; }
        public string P6Name { get; set; }
        public string P6Uni { get; set; }
        public string P6Pos { get; set; }
        public int P6X { get; set; }
        public int P6Y { get; set; }
        public int P7ID { get; set; }
        public string P7Name { get; set; }
        public string P7Uni { get; set; }
        public string P7Pos { get; set; }
        public int P7X { get; set; }
        public int P7Y { get; set; }
        public int P8ID { get; set; }
        public string P8Name { get; set; }
        public string P8Uni { get; set; }
        public string P8Pos { get; set; }
        public int P8X { get; set; }
        public int P8Y { get; set; }
        public int P9ID { get; set; }
        public string P9Name { get; set; }
        public string P9Uni { get; set; }
        public string P9Pos { get; set; }
        public int P9X { get; set; }
        public int P9Y { get; set; }
        public int P10ID { get; set; }
        public string P10Name { get; set; }
        public string P10Uni { get; set; }
        public string P10Pos { get; set; }
        public int P10X { get; set; }
        public int P10Y { get; set; }
        public int P11ID { get; set; }
        public string P11Name { get; set; }
        public string P11Uni { get; set; }
        public string P11Pos { get; set; }
        public int P11X { get; set; }
        public int P11Y { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
