//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerInfoIR
    {
        public int PlayerInfoIRId { get; set; }
        public int TeamInfoIRId { get; set; }
        public int PlayerID { get; set; }
        public string PlayerName { get; set; }
        public string PlayerNameS { get; set; }
        public string Pos { get; set; }
        public int UpdateDate { get; set; }
        public string PartName { get; set; }
        public string PartNameDetails { get; set; }
        public string InjulyDate { get; set; }
        public string InjulyRank { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
