//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerInfoDI
    {
        public int PlayerInfoDIId { get; set; }
        public int DirectoryDIId { get; set; }
        public int PlayerNo { get; set; }
        public int PlayerID { get; set; }
        public string RealName { get; set; }
        public string RealNameK { get; set; }
        public string PlayerName { get; set; }
        public string PlayerNameS { get; set; }
        public string PlayerNameKS { get; set; }
        public string PlayerNameE { get; set; }
        public string PlayerNameES { get; set; }
        public string UniformNO { get; set; }
        public string Position { get; set; }
        public Nullable<int> Class { get; set; }
        public Nullable<short> NewcomerFlag { get; set; }
        public string HomeTown { get; set; }
        public string Blood { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Birthday { get; set; }
        public string Career { get; set; }
        public string IndividualTitle { get; set; }
        public string PlayerTeamHistory { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
