//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerInfoLPNO
    {
        public int PlayerInfoLPNOId { get; set; }
        public int NowOrderInfoLPId { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public string NameS { get; set; }
        public string Uni { get; set; }
        public string Pos { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Yellow { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
