//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerInfoDA
    {
        public int PlayerInfoDAId { get; set; }
        public int DirectoryDAId { get; set; }
        public int PlayerNo { get; set; }
        public int PlayerID { get; set; }
        public string PlayerName { get; set; }
        public Nullable<int> Class { get; set; }
        public Nullable<int> FirstDate { get; set; }
        public Nullable<int> Acap { get; set; }
        public Nullable<int> Agoal { get; set; }
        public Nullable<int> Speed { get; set; }
        public Nullable<int> Physical { get; set; }
        public Nullable<int> Technic { get; set; }
        public Nullable<int> Mental { get; set; }
        public Nullable<int> Tactics { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
