//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerLS
    {
        public int PlayerLSId { get; set; }
        public int TeamInfoLSId { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public string NameS { get; set; }
        public string Uni { get; set; }
        public string Pos { get; set; }
        public Nullable<int> StartF { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> FKScore { get; set; }
        public Nullable<int> PKScore { get; set; }
        public Nullable<int> OwnGoal { get; set; }
        public Nullable<int> Shoot { get; set; }
        public Nullable<int> Assist { get; set; }
        public Nullable<int> Lost { get; set; }
        public Nullable<int> SufferShoot { get; set; }
        public Nullable<int> Yellow { get; set; }
        public Nullable<int> Red { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<int> SeasonGame { get; set; }
        public Nullable<int> SeasonTime { get; set; }
        public Nullable<int> SeasonScore { get; set; }
        public Nullable<int> SeasonLost { get; set; }
        public Nullable<int> ShootGoal { get; set; }
        public Nullable<int> Pass { get; set; }
        public Nullable<int> Foul { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
