//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerInfoPS
    {
        public int PlayerInfoPSId { get; set; }
        public int PlayerStatsReportPSId { get; set; }
        public int PlayerID { get; set; }
        public string PlayerName { get; set; }
        public string PlayerNameS { get; set; }
        public Nullable<int> Game { get; set; }
        public Nullable<int> StartG { get; set; }
        public Nullable<int> FullG { get; set; }
        public Nullable<int> ChangeG { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<int> Goal { get; set; }
        public Nullable<int> GoalFK { get; set; }
        public Nullable<int> GoalPK { get; set; }
        public Nullable<int> GoalCK { get; set; }
        public Nullable<int> GoalRight { get; set; }
        public Nullable<int> GoalLeft { get; set; }
        public Nullable<int> GoalHead { get; set; }
        public Nullable<int> GoalOther { get; set; }
        public Nullable<int> Shoot { get; set; }
        public Nullable<int> Assist { get; set; }
        public Nullable<int> Yellow { get; set; }
        public Nullable<int> Red { get; set; }
        public Nullable<int> Lose { get; set; }
        public Nullable<int> SufferShoot { get; set; }
        public Nullable<int> Win { get; set; }
        public Nullable<int> Lost { get; set; }
        public Nullable<int> Draw { get; set; }
        public Nullable<int> TotalGame { get; set; }
        public Nullable<int> TotalTime { get; set; }
        public Nullable<int> TotalGoal { get; set; }
        public Nullable<int> TotalLose { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
