//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultInfoT5
    {
        public int ResultInfoT5Id { get; set; }
        public int Team5thGameReportT5Id { get; set; }
        public int GameDate { get; set; }
        public Nullable<short> HV { get; set; }
        public Nullable<int> ID { get; set; }
        public string NameS { get; set; }
        public Nullable<int> StadiumID { get; set; }
        public string StadiumNameS { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> PKScore { get; set; }
        public Nullable<int> Lose { get; set; }
        public Nullable<int> PKLose { get; set; }
        public string GameResult { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
