//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultInfoTH
    {
        public int ResultInfoTHId { get; set; }
        public int TeamInfoTHId { get; set; }
        public short HV { get; set; }
        public int Game { get; set; }
        public int Point { get; set; }
        public int Win { get; set; }
        public Nullable<int> Win90 { get; set; }
        public Nullable<int> WinEX { get; set; }
        public Nullable<int> WinPK { get; set; }
        public int Lose { get; set; }
        public Nullable<int> Lose90 { get; set; }
        public Nullable<int> LoseEX { get; set; }
        public Nullable<int> LosePK { get; set; }
        public int Draw { get; set; }
        public int Score { get; set; }
        public int Lost { get; set; }
        public int Differ { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
