//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultInfoHE
    {
        public int ResultInfoHEId { get; set; }
        public int ScheduleInfoHEId { get; set; }
        public int GameDate { get; set; }
        public int HomeTeamID { get; set; }
        public string HomeTeamNameS { get; set; }
        public Nullable<int> AwayTeamID { get; set; }
        public string AwayTeamNameS { get; set; }
        public Nullable<int> StadiumID { get; set; }
        public string StadiumNameS { get; set; }
        public Nullable<int> HomeScore { get; set; }
        public Nullable<int> HomePKScore { get; set; }
        public Nullable<int> AwayScore { get; set; }
        public Nullable<int> AwayPKScore { get; set; }
        public string GameResult { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
