//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultInfoSS
    {
        public int ResultInfoSSId { get; set; }
        public int TeamSeasonReportSSId { get; set; }
        public short SeasonNo { get; set; }
        public int Year { get; set; }
        public int GameKindID { get; set; }
        public string GameKindName { get; set; }
        public Nullable<int> SeasonID { get; set; }
        public string SeasonName { get; set; }
        public Nullable<int> Game { get; set; }
        public Nullable<int> Point { get; set; }
        public Nullable<int> Win { get; set; }
        public Nullable<int> Win90 { get; set; }
        public Nullable<int> WinEX { get; set; }
        public Nullable<int> WinPK { get; set; }
        public Nullable<int> Lose { get; set; }
        public Nullable<int> Lose90 { get; set; }
        public Nullable<int> LoseEX { get; set; }
        public Nullable<int> LosePK { get; set; }
        public Nullable<int> Draw { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<int> Lost { get; set; }
        public Nullable<int> Differ { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
