//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleInfo
    {
        public int ScheduleInfoId { get; set; }
        public int GameCategoryId { get; set; }
        public int ScheduleNO { get; set; }
        public int GameID { get; set; }
        public Nullable<int> GameDate { get; set; }
        public Nullable<int> GameTime { get; set; }
        public Nullable<int> LocalDate { get; set; }
        public Nullable<int> LocalTime { get; set; }
        public Nullable<int> OccasionNo { get; set; }
        public Nullable<int> Round { get; set; }
        public string RoundName { get; set; }
        public string GroupID { get; set; }
        public Nullable<short> Subject { get; set; }
        public Nullable<short> DayNight { get; set; }
        public Nullable<int> StadiumID { get; set; }
        public string StadiumName { get; set; }
        public string StadiumNameS { get; set; }
        public string Site { get; set; }
        public Nullable<int> HomeTeamID { get; set; }
        public string HomeTeamName { get; set; }
        public string HomeTeamNameS { get; set; }
        public string HomeTeamNameE { get; set; }
        public string HomeTeamNameES { get; set; }
        public Nullable<int> AwayTeamID { get; set; }
        public string AwayTeamName { get; set; }
        public string AwayTeamNameS { get; set; }
        public string AwayTeamNameE { get; set; }
        public string AwayTeamNameES { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
