//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleInfoHE
    {
        public int ScheduleInfoHEId { get; set; }
        public int GameCategoryHEId { get; set; }
        public int ScheduleNO { get; set; }
        public int GameID { get; set; }
        public Nullable<int> HomeTeamID { get; set; }
        public string HomeTeamNameS { get; set; }
        public Nullable<int> AwayTeamID { get; set; }
        public string AwayTeamNameS { get; set; }
        public Nullable<int> Game { get; set; }
        public Nullable<int> HomeWin { get; set; }
        public Nullable<int> HomeWin90 { get; set; }
        public Nullable<int> HomeWinEX { get; set; }
        public Nullable<int> HomeWinPK { get; set; }
        public string HomeScore { get; set; }
        public Nullable<int> AwayWin { get; set; }
        public Nullable<int> AwayWin90 { get; set; }
        public Nullable<int> AwayWinEX { get; set; }
        public Nullable<int> AwayWinPK { get; set; }
        public string AwayScore { get; set; }
        public Nullable<int> Draw { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
