//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StartingInfoLP
    {
        public int StartingInfoLPId { get; set; }
        public int PlayerReportLPId { get; set; }
        public short HV { get; set; }
        public Nullable<int> FormationID { get; set; }
        public string FormationName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
