//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuspensionInfoSR
    {
        public int SuspensionInfoSRId { get; set; }
        public int SuspendReportSRId { get; set; }
        public int No { get; set; }
        public int TeamID { get; set; }
        public string TeamNameS { get; set; }
        public int PlayerID { get; set; }
        public string PlayerName { get; set; }
        public string PlayerNameS { get; set; }
        public int GamesC { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
