//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamInfoTE
    {
        public int TeamInfoTEId { get; set; }
        public int TeamMSTTEId { get; set; }
        public int TeamNo { get; set; }
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public string TeamNameS { get; set; }
        public string TeamNameE { get; set; }
        public string TeamNameES { get; set; }
        public string TeamNameK { get; set; }
        public string TeamNameKS { get; set; }
        public string Post { get; set; }
        public string Address { get; set; }
        public string Telephone { get; set; }
        public Nullable<int> HomeStadiumID { get; set; }
        public string HomeStadiumName { get; set; }
        public string HomeStadiumAddress { get; set; }
        public string Color { get; set; }
        public Nullable<int> Founded { get; set; }
        public string Formation { get; set; }
        public string IndividualTitle { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
