//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamSeasonStats
    {
        public int GameKindID { get; set; }
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public int TotalScore { get; set; }
        public int GoalCount { get; set; }
        public int PKGoalCount { get; set; }
        public int SetPlayDirectGoalCount { get; set; }
        public int SetPlayGoalCount { get; set; }
        public int CrossGoalCount { get; set; }
        public int ThroughPassGoalCount { get; set; }
        public int ShortPassGoalCount { get; set; }
        public int LongPassGoalCount { get; set; }
        public int DribbleGoalCount { get; set; }
        public int LooseBallGoalCount { get; set; }
        public int OtherGoalCount { get; set; }
        public int ShootCount { get; set; }
        public int WithinShootCount { get; set; }
        public double ShootDecisionRatio { get; set; }
        public double ShootWithinRatio { get; set; }
        public double PossessionRatio { get; set; }
        public int PassCount { get; set; }
        public int PassSuccessCount { get; set; }
        public double PassSuccessRatio { get; set; }
        public int ShortPassCount { get; set; }
        public double ShortPassRatio { get; set; }
        public int MiddlePassCount { get; set; }
        public double MiddlePassRatio { get; set; }
        public int LongPassCount { get; set; }
        public double LongPassRatio { get; set; }
        public int FrontPassCount { get; set; }
        public double FrontPassRatio { get; set; }
        public int RightSidePassCount { get; set; }
        public double RightSidePassRatio { get; set; }
        public int BackwardPassCount { get; set; }
        public double BackwardPassRatio { get; set; }
        public int LeftSidePassCount { get; set; }
        public double LeftSidePassRatio { get; set; }
        public int CrossCount { get; set; }
        public int LeftSideCrossCount { get; set; }
        public int RightSideCrossCount { get; set; }
        public int TackleCount { get; set; }
        public int ClearCount { get; set; }
        public int InterceptCount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int LostCount { get; set; }
        public int PKLostCount { get; set; }
        public int SetPlayDirectLostCount { get; set; }
        public int SetPlayLostCount { get; set; }
        public int CrossLostCount { get; set; }
        public int ThroughPassLostCount { get; set; }
        public int ShortPassLostCount { get; set; }
        public int LongPassLostCount { get; set; }
        public int DribbleLostCount { get; set; }
        public int LooseBallLostCount { get; set; }
        public int OtherLostCount { get; set; }
        public int FreeKickCount { get; set; }
        public int CornerKickCount { get; set; }
    }
}
