//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamGameStats
    {
        public int GameID { get; set; }
        public int GameDate { get; set; }
        public int GameKindID { get; set; }
        public int OccasionNo { get; set; }
        public int HomeAwayClass { get; set; }
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public int OpponentTeamID { get; set; }
        public string OpponentTeamName { get; set; }
        public int GameResultID { get; set; }
        public int PlayCount { get; set; }
        public int GoalCount { get; set; }
        public int OGCount { get; set; }
        public int ShootCount { get; set; }
        public int WithinShootCount { get; set; }
        public double PossessionRatio { get; set; }
        public int PassCount { get; set; }
        public int CrossCount { get; set; }
        public int LeftSideCrossCount { get; set; }
        public int RightSideCrossCount { get; set; }
        public int DribbleCount { get; set; }
        public int TackleCount { get; set; }
        public int ClearCount { get; set; }
        public int InterceptCount { get; set; }
        public int FoulCount { get; set; }
        public int C30mLineCount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
