//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamInfoLS
    {
        public int TeamInfoLSId { get; set; }
        public int StatsReportLSId { get; set; }
        public short HV { get; set; }
        public int ID { get; set; }
        public string NameS { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
