//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Jleague.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarningInfoLG
    {
        public int WarningInfoLGId { get; set; }
        public int GameReportLGId { get; set; }
        public int No { get; set; }
        public int StateID { get; set; }
        public string StateName { get; set; }
        public Nullable<int> Time { get; set; }
        public Nullable<int> Half { get; set; }
        public Nullable<int> TeamID { get; set; }
        public string TeamNameS { get; set; }
        public Nullable<int> PlayerID { get; set; }
        public string PlayerName { get; set; }
        public string PlayerNameS { get; set; }
        public string PlayerUni { get; set; }
        public Nullable<short> Divide { get; set; }
        public Nullable<short> SecondF { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
