//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18408
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Core.Models.Flotr2.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Flotr2ScriptPartsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Flotr2ScriptPartsResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Splg.Core.Models.Flotr2.Resources.Flotr2ScriptPartsResource", typeof(Flotr2ScriptPartsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///         {
        ///        data : @Data,
        ///        bubbles : {
        ///			show : @BubblesIsVisible,
        ///			baseRadius : @BubblesBaseRadius
        ///		},
        ///		mouse : {
        ///			track : @MouseIsTrackable,
        ///			trackFormatter : @MouseTrackFormatter
        ///		}
        ///	  } に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormationBubblesTemplete {
            get {
                return ResourceManager.GetString("FormationBubblesTemplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   		  function (o) {
        ///            var Label@Suffix = @Data;
        ///            return Label@Suffix[o.index]; 
        ///          } に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormationLabelFormatterFunction {
            get {
                return ResourceManager.GetString("FormationLabelFormatterFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///         {
        ///        data : @Data,
        ///        markers : {
        ///          show: @MarkersProperties.Markers.IsVisible
        ///          relative: @MarkersProperties.Markers.IsRelative,
        ///          fontSize: @MarkersProperties.Markers.FontSize,
        ///          labelFormatter : @MarkersLabelFormatter
        ///  		}
        ///	  } に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormationMarkersTemplete {
            get {
                return ResourceManager.GetString("FormationMarkersTemplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {
        ///	xaxis   : { 
        ///		  min : @XAxisMinValue,
        ///		  max : @XAxisMaxValue,
        ///		  showLabels : @XAxisIsVisibleLabels
        ///	},
        ///	yaxis   : { 
        ///		  min : @YAxisMinValue,
        ///		  max : @YAxisMaxValue,
        ///		  showLabels : @YAxisIsVisibleLabels
        ///	},
        ///	grid : { 
        ///		  backgroundImage: @GridBackGroundImageAddress,
        ///		  verticalLines: @GridIsVisibleVerticalLines, 
        ///		  horizontalLines: @GridIsVisibleHorizontalLines
        ///	}
        ///
        ///} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormationSharedTemplete {
            get {
                return ResourceManager.GetString("FormationSharedTemplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   function (e){
        ///                var PlayerID@Suffix = @PlayerIDList;
        ///				var ValueName@Suffix = @ValueList;
        ///                x = e.x;
        ///                y = e.y;
        ///				z = ValueName@Suffix[e.index];
        ///                url = &quot;https://spolog.jp/jleague/players/&quot; + PlayerID@Suffix[e.index] + &quot;/&quot;;
        ///            } に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormationTrackFormatterFunction {
            get {
                return ResourceManager.GetString("FormationTrackFormatterFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   { data : @Data, label : &apos;@Label&apos; }, に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PieChartDataSourceTemplete {
            get {
                return ResourceManager.GetString("PieChartDataSourceTemplete", resourceCulture);
            }
        }
    }
}
