//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18408
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Core.Models.Flotr2.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Flotr2ScriptResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Flotr2ScriptResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Splg.Core.Models.Flotr2.Resources.Flotr2ScriptResource", typeof(Flotr2ScriptResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BarChartScriptTemplete {
            get {
                return ResourceManager.GetString("BarChartScriptTemplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BubbleChartScriptTemplete {
            get {
                return ResourceManager.GetString("BubbleChartScriptTemplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   var x = 0;
        ///var y = 0;
        ///var url;
        ///
        ///(function basic_bubble(container) {
        /// var
        ///      bubblesHome = {
        ///        data : @bubbles.HomePosition,
        ///        bubbles : @bubbles.HomePropaties,
        ///		mouse : @mouse.HomePropaties
        ///	  },
        ///      bubblesAway = {
        ///        data : @bubbles.AwayPosition,
        ///        bubbles : @bubbles.AwayPropaties,
        ///		mouse : @mouse.AwayPropaties
        ///      }, 
        ///      markersHomePlayerName = {
        ///        data : @markers.HomePlayerNamePosition,
        ///        markers: @markers.HomePlayerNamePropaties
        ///      }, [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FormationChartScriptTemplete {
            get {
                return ResourceManager.GetString("FormationChartScriptTemplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;script type=&quot;text/javascript&quot;&gt;
        ///    (function basic_pie(container) 
        ///    {
        ///        var
        ///          d1 = [[0, 4]],
        ///          d2 = [[0, 3]],
        ///          d3 = [[0, 1]],
        ///          d4 = [[0, 4]],
        ///          graph;
        ///
        ///        graph = Flotr.draw(container, 
        ///        [
        ///          { data : d1, label : &apos;Comedy&apos; },
        ///          { data : d2, label : &apos;Action&apos; },
        ///          { data : d3, label : &apos;Romance&apos;},
        ///          { data : d4, label : &apos;Drama&apos; }
        ///        ]
        ///        , 
        ///        {
        ///            HtmlText : false,
        ///         [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PieChartScriptTemplete {
            get {
                return ResourceManager.GetString("PieChartScriptTemplete", resourceCulture);
            }
        }
    }
}
