//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Japanese {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Japanese() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Japanese", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 【スポログ】お問い合わせ.
        /// </summary>
        internal static string defaultValueTitleEmailContact {
            get {
                return ResourceManager.GetString("defaultValueTitleEmailContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力されたパスワードが違います。.
        /// </summary>
        internal static string errorComparePassword {
            get {
                return ResourceManager.GetString("errorComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to このメールアドレスは既に登録されています。.
        /// </summary>
        internal static string errorEmailExists {
            get {
                return ResourceManager.GetString("errorEmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 入力メールアドレスが存在していない。.
        /// </summary>
        internal static string errorEmailWithoutExist {
            get {
                return ResourceManager.GetString("errorEmailWithoutExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メールアドレスが違います。.
        /// </summary>
        internal static string errorInvalidEmail {
            get {
                return ResourceManager.GetString("errorInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードは6文字以上32文字以下の半角英数字を入力下さい。.
        /// </summary>
        internal static string errorLengthPassword {
            get {
                return ResourceManager.GetString("errorLengthPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メールアドレスまたはパスワードが一致しません。.
        /// </summary>
        internal static string errorLogin {
            get {
                return ResourceManager.GetString("errorLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 確認のパスワードを入力してください。.
        /// </summary>
        internal static string errorRequiredConfirmPass {
            get {
                return ResourceManager.GetString("errorRequiredConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本文を入力してください。.
        /// </summary>
        internal static string errorRequiredContentEmail {
            get {
                return ResourceManager.GetString("errorRequiredContentEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メールアドレスを入力してください。.
        /// </summary>
        internal static string errorRequiredEmail {
            get {
                return ResourceManager.GetString("errorRequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パスワードを入力してください。.
        /// </summary>
        internal static string errorRequiredPass {
            get {
                return ResourceManager.GetString("errorRequiredPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メール送信完了しました。.
        /// </summary>
        internal static string messSendEmailSucess {
            get {
                return ResourceManager.GetString("messSendEmailSucess", resourceCulture);
            }
        }
    }
}
