//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BattingAverageBest10
    {
        public long BattingAverageBest10Id { get; set; }
        public long BattingAverageBest10HeaderId { get; set; }
        public int Ranking { get; set; }
        public int PlayerCD { get; set; }
        public string Name { get; set; }
        public string ShortNamePlayer { get; set; }
        public string Num { get; set; }
        public Nullable<int> TeamCD { get; set; }
        public string ShortNameTeam { get; set; }
        public string TeamInitial { get; set; }
        public string BattingAverage { get; set; }
        public Nullable<int> Game { get; set; }
        public Nullable<int> PlateAppearance { get; set; }
        public Nullable<int> AtBat { get; set; }
        public Nullable<int> Run { get; set; }
        public Nullable<int> Hit { get; set; }
        public Nullable<int> Double { get; set; }
        public Nullable<int> Triple { get; set; }
        public Nullable<int> Homerun { get; set; }
        public Nullable<int> Base { get; set; }
        public Nullable<int> RunsBattingIn { get; set; }
        public Nullable<int> WinningRunsBattedIn { get; set; }
        public Nullable<int> StrikeOut { get; set; }
        public Nullable<int> BaseOnBall { get; set; }
        public Nullable<int> HitByPitch { get; set; }
        public Nullable<int> SacrificeHit { get; set; }
        public Nullable<int> SacrificeFly { get; set; }
        public Nullable<int> StolenBase { get; set; }
        public Nullable<int> TGIDP { get; set; }
        public Nullable<int> Error { get; set; }
        public string TBAWRIS { get; set; }
        public string OnBase { get; set; }
        public string Slugging { get; set; }
        public string Ops { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
