//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatcherGL
    {
        public long CatcherGLId { get; set; }
        public long ReliefInfoGLId { get; set; }
        public int No { get; set; }
        public int ID { get; set; }
        public string Num { get; set; }
        public string NameS { get; set; }
        public string NameL { get; set; }
        public Nullable<int> TeamID { get; set; }
        public string TeamS { get; set; }
        public string TeamES { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
