//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentGameCO
    {
        public long CommentGameCOId { get; set; }
        public int GameDate { get; set; }
        public short CommentF { get; set; }
        public short MEPF { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
