//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailsGL
    {
        public long DetailsGLId { get; set; }
        public long PlayerGLId { get; set; }
        public int TotalC { get; set; }
        public Nullable<short> Run { get; set; }
        public Nullable<int> Inn { get; set; }
        public Nullable<short> TB { get; set; }
        public Nullable<short> RHR { get; set; }
        public Nullable<short> Direction { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
