//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameInfoCO
    {
        public long GameInfoCOId { get; set; }
        public long CommentGameCOId { get; set; }
        public int GameID { get; set; }
        public Nullable<int> Year { get; set; }
        public string GameKindName { get; set; }
        public string StadiumName { get; set; }
        public string StadiumNameS { get; set; }
        public Nullable<int> Round { get; set; }
        public Nullable<int> StartTime { get; set; }
        public Nullable<int> EndTime { get; set; }
        public Nullable<int> Atendance { get; set; }
        public Nullable<short> GameSection { get; set; }
        public Nullable<int> Inning { get; set; }
        public Nullable<short> TB { get; set; }
        public Nullable<short> Xflag { get; set; }
        public string GameEndState { get; set; }
        public Nullable<short> CompleteF { get; set; }
        public string GameComment { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
