//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameInfoPSP
    {
        public long GameInfoPSPId { get; set; }
        public int GameID { get; set; }
        public int GameKindID { get; set; }
        public string GameKindName { get; set; }
        public Nullable<int> GameDate { get; set; }
        public Nullable<short> WeekDay { get; set; }
        public Nullable<int> StartTime { get; set; }
        public Nullable<int> StadiumID { get; set; }
        public string StadiumName { get; set; }
        public Nullable<int> Round { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
