//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameEndInfoGTS
    {
        public long GameEndInfoGTSId { get; set; }
        public long GameInfoGTSId { get; set; }
        public int ResultID { get; set; }
        public Nullable<int> EndTime { get; set; }
        public string WinPitcher { get; set; }
        public string LosePitcher { get; set; }
        public string SavePitcher { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
