//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameInfoSS
    {
        public long GameInfoSSId { get; set; }
        public long MonthGroupSSId { get; set; }
        public int SeqNo { get; set; }
        public int ID { get; set; }
        public int GameDate { get; set; }
        public int Week { get; set; }
        public string Time { get; set; }
        public Nullable<int> StadiumID { get; set; }
        public string StadiumName { get; set; }
        public string StadiumNameS { get; set; }
        public Nullable<int> Round { get; set; }
        public Nullable<short> DoubleHeaderF { get; set; }
        public Nullable<short> DayNight { get; set; }
        public Nullable<int> GamesDateNo { get; set; }
        public Nullable<int> GamesSeqNo { get; set; }
        public string GameName { get; set; }
        public Nullable<short> GameState { get; set; }
        public Nullable<short> GameResult { get; set; }
        public Nullable<int> HomeScore { get; set; }
        public Nullable<int> VisitorScore { get; set; }
        public Nullable<int> HomeTeamID { get; set; }
        public string HomeTeamName { get; set; }
        public string HomeTeamNameS { get; set; }
        public string HomeTeamNameE { get; set; }
        public string HomeTeamNameES { get; set; }
        public string HomeTeamInitial { get; set; }
        public Nullable<int> VisitorTeamID { get; set; }
        public string VisitorTeamName { get; set; }
        public string VisitorTeamNameS { get; set; }
        public string VisitorTeamNameE { get; set; }
        public string VisitorTeamNameES { get; set; }
        public string VisitorTeamInitial { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
