//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GWRBIRGI
    {
        public long GWRBIRGIId { get; set; }
        public long GameResultInfoRGIId { get; set; }
        public int PlayerCD { get; set; }
        public string ShortNamePlayer { get; set; }
        public Nullable<int> Round { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
