//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HittingStats3YearsInfo
    {
        public long HittingStats3YearsInfoId { get; set; }
        public long HittingStats3YearsId { get; set; }
        public int Year { get; set; }
        public int TeamID { get; set; }
        public string TeamS { get; set; }
        public string TeamES { get; set; }
        public string AVG { get; set; }
        public Nullable<int> G { get; set; }
        public Nullable<int> AB { get; set; }
        public Nullable<int> R { get; set; }
        public Nullable<int> H { get; set; }
        public Nullable<int> HR { get; set; }
        public Nullable<int> RBI { get; set; }
        public Nullable<int> SO { get; set; }
        public Nullable<int> BB { get; set; }
        public Nullable<int> HBP { get; set; }
        public Nullable<int> SH { get; set; }
        public Nullable<int> SF { get; set; }
        public Nullable<int> SB { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
