//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HittingStats6thGameInfo
    {
        public long HittingStats6thGameInfoId { get; set; }
        public long HittingStats6thGameId { get; set; }
        public int TeamsOpponentCD { get; set; }
        public string ShortNameTeamsOpponent { get; set; }
        public Nullable<int> Round { get; set; }
        public Nullable<int> GameDate { get; set; }
        public Nullable<int> PlateAppearance { get; set; }
        public Nullable<int> AtBat { get; set; }
        public Nullable<int> Run { get; set; }
        public Nullable<int> Hit { get; set; }
        public Nullable<int> Homerun { get; set; }
        public Nullable<int> RunsBattingIn { get; set; }
        public Nullable<int> GWRBI { get; set; }
        public Nullable<int> StrikeOut { get; set; }
        public Nullable<int> BaseOnBall { get; set; }
        public Nullable<int> HitByPitch { get; set; }
        public string BatingResult1 { get; set; }
        public string BatingResult2 { get; set; }
        public string BatingResult3 { get; set; }
        public string BatingResult4 { get; set; }
        public string BatingResult5 { get; set; }
        public string BatingResult6 { get; set; }
        public string BatingResult7 { get; set; }
        public string BatingResult8 { get; set; }
        public string BatingResult9 { get; set; }
        public string BatingResult10 { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
