//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HittingStats3Years
    {
        public long HittingStats3YearsId { get; set; }
        public long HittingStats3YearsTeamsId { get; set; }
        public int ID { get; set; }
        public string NameS { get; set; }
        public string NameL { get; set; }
        public Nullable<short> Pos { get; set; }
        public Nullable<short> DataF { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
