//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HittingStatsTeamDifferenceInfo
    {
        public long HittingStatsTeamDifferenceInfoId { get; set; }
        public long HittingStatsTeamDifferenceId { get; set; }
        public int TeamsOpponentCD { get; set; }
        public string ShortNameTeamsOpponent { get; set; }
        public string BattingAverage { get; set; }
        public Nullable<int> Game { get; set; }
        public Nullable<int> PlateAppearance { get; set; }
        public Nullable<int> AtBat { get; set; }
        public Nullable<int> Hit { get; set; }
        public Nullable<int> Double { get; set; }
        public Nullable<int> Triple { get; set; }
        public Nullable<int> Homerun { get; set; }
        public Nullable<int> RunsBattingIn { get; set; }
        public Nullable<int> StrikeOut { get; set; }
        public Nullable<int> BaseOnBall { get; set; }
        public Nullable<int> HitByPitch { get; set; }
        public Nullable<int> SacrificeHit { get; set; }
        public Nullable<int> SacrificeFly { get; set; }
        public Nullable<int> StolenBase { get; set; }
        public Nullable<int> DoublePlay { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
