//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HittingStatsScoringPosition
    {
        public long HittingStatsScoringPositionId { get; set; }
        public long HittingStatsScoringPositionHeaderId { get; set; }
        public int TeamCD { get; set; }
        public string ShortNameTeam { get; set; }
        public Nullable<int> PlayerCD { get; set; }
        public string Name { get; set; }
        public string ShortNamePlayer { get; set; }
        public string Num { get; set; }
        public string BattingAverage { get; set; }
        public Nullable<int> PlateAppearance { get; set; }
        public Nullable<int> AtBat { get; set; }
        public Nullable<int> Hit { get; set; }
        public Nullable<int> Homerun { get; set; }
        public Nullable<int> RunsBattingIn { get; set; }
        public Nullable<int> StrikeOut { get; set; }
        public Nullable<int> BaseOnBall { get; set; }
        public Nullable<int> HitByPitch { get; set; }
        public Nullable<int> SacrificeHit { get; set; }
        public Nullable<int> SacrificeFly { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
