//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomerunBest10
    {
        public long HomerunBest10Id { get; set; }
        public long HomerunBest10HeaderId { get; set; }
        public int Ranking { get; set; }
        public int PlayerCD { get; set; }
        public string Name { get; set; }
        public string ShortNamePlayer { get; set; }
        public string Num { get; set; }
        public Nullable<int> TeamCD { get; set; }
        public string ShortNameTeam { get; set; }
        public string TeamInitial { get; set; }
        public Nullable<int> HomeRun { get; set; }
        public Nullable<int> AtBat { get; set; }
        public string HomerunPace { get; set; }
        public string BattingAverage { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
