//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomerunInfoRGI
    {
        public long HomerunInfoRGIId { get; set; }
        public long RealGameInfoRootRGIId { get; set; }
        public int TeamCD { get; set; }
        public string ShortNameTeam { get; set; }
        public Nullable<int> PlayerCD { get; set; }
        public string ShortNamePlayer { get; set; }
        public Nullable<int> TotalHomerun { get; set; }
        public Nullable<int> runsbattedin { get; set; }
        public Nullable<int> MatterInning { get; set; }
        public Nullable<int> PitchersOpponentCD { get; set; }
        public string ShortNamePitchersOpponent { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
