//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InningScoreInfoCO
    {
        public long InningScoreInfoCOId { get; set; }
        public long TeamInfoCOId { get; set; }
        public int Inning { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<short> Xflag { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
