//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerInfoST
    {
        public long ManagerInfoSTId { get; set; }
        public long StartingGameSTId { get; set; }
        public int HomeManagerID { get; set; }
        public string HomeManagerNumber { get; set; }
        public string HomeManagerNameS { get; set; }
        public string HomeManagerNameL { get; set; }
        public Nullable<int> VisitorManagerID { get; set; }
        public string VisitorManagerNumber { get; set; }
        public string VisitorManagerNameS { get; set; }
        public string VisitorManagerNameL { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
