//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoteInfoGL
    {
        public long NoteInfoGLId { get; set; }
        public long GameLiveGLId { get; set; }
        public short Type { get; set; }
        public short HV { get; set; }
        public int Inning { get; set; }
        public int PlayerID { get; set; }
        public string BackNumber { get; set; }
        public string PlayerNameS { get; set; }
        public string PlayerNameL { get; set; }
        public Nullable<int> TeamID { get; set; }
        public string TeamS { get; set; }
        public string TeamES { get; set; }
        public Nullable<int> HostTeamID { get; set; }
        public string HostTeamS { get; set; }
        public string HostTeamES { get; set; }
        public Nullable<int> VsPlayerID { get; set; }
        public string VsBackNumber { get; set; }
        public string VsPlayerNameS { get; set; }
        public string VsPlayerNameL { get; set; }
        public Nullable<int> VsTeamID { get; set; }
        public string VsTeamS { get; set; }
        public string VsTeamES { get; set; }
        public Nullable<int> VsHostTeamID { get; set; }
        public string VsHostTeamS { get; set; }
        public string VsHostTeamES { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
