//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class NpbEntities : DbContext
    {
        public NpbEntities()
            : base("name=NpbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BatGTE> BatGTE { get; set; }
        public virtual DbSet<BatGTS> BatGTS { get; set; }
        public virtual DbSet<BattingAverageBest10> BattingAverageBest10 { get; set; }
        public virtual DbSet<BattingAverageBest10Header> BattingAverageBest10Header { get; set; }
        public virtual DbSet<CatcherGL> CatcherGL { get; set; }
        public virtual DbSet<CommentGameCO> CommentGameCO { get; set; }
        public virtual DbSet<DefenceLocationMST> DefenceLocationMST { get; set; }
        public virtual DbSet<DetailsGL> DetailsGL { get; set; }
        public virtual DbSet<Directory> Directory { get; set; }
        public virtual DbSet<DSMEPInfoCO> DSMEPInfoCO { get; set; }
        public virtual DbSet<EarnedRunAverageBest10> EarnedRunAverageBest10 { get; set; }
        public virtual DbSet<EarnedRunAverageBest10Header> EarnedRunAverageBest10Header { get; set; }
        public virtual DbSet<ExhibitionGameStats> ExhibitionGameStats { get; set; }
        public virtual DbSet<ExhibitionGameStatsHeader> ExhibitionGameStatsHeader { get; set; }
        public virtual DbSet<GameClassMST> GameClassMST { get; set; }
        public virtual DbSet<GameEndInfoGL> GameEndInfoGL { get; set; }
        public virtual DbSet<GameEndInfoGTE> GameEndInfoGTE { get; set; }
        public virtual DbSet<GameEndInfoGTS> GameEndInfoGTS { get; set; }
        public virtual DbSet<GameInfoCO> GameInfoCO { get; set; }
        public virtual DbSet<GameInfoGL> GameInfoGL { get; set; }
        public virtual DbSet<GameInfoGTE> GameInfoGTE { get; set; }
        public virtual DbSet<GameInfoGTS> GameInfoGTS { get; set; }
        public virtual DbSet<GameInfoPSP> GameInfoPSP { get; set; }
        public virtual DbSet<GameInfoRGI> GameInfoRGI { get; set; }
        public virtual DbSet<GameInfoSS> GameInfoSS { get; set; }
        public virtual DbSet<GameInfoSSN> GameInfoSSN { get; set; }
        public virtual DbSet<GameLiveGL> GameLiveGL { get; set; }
        public virtual DbSet<GameOrderGO> GameOrderGO { get; set; }
        public virtual DbSet<GameResultInfoRGI> GameResultInfoRGI { get; set; }
        public virtual DbSet<GWRBIPlayerGL> GWRBIPlayerGL { get; set; }
        public virtual DbSet<GWRBIRGI> GWRBIRGI { get; set; }
        public virtual DbSet<HittingStats> HittingStats { get; set; }
        public virtual DbSet<HittingStats3Years> HittingStats3Years { get; set; }
        public virtual DbSet<HittingStats3YearsInfo> HittingStats3YearsInfo { get; set; }
        public virtual DbSet<HittingStats3YearsTeams> HittingStats3YearsTeams { get; set; }
        public virtual DbSet<HittingStats5thGame> HittingStats5thGame { get; set; }
        public virtual DbSet<HittingStats5thGameHeader> HittingStats5thGameHeader { get; set; }
        public virtual DbSet<HittingStats6thGame> HittingStats6thGame { get; set; }
        public virtual DbSet<HittingStats6thGameHeader> HittingStats6thGameHeader { get; set; }
        public virtual DbSet<HittingStats6thGameInfo> HittingStats6thGameInfo { get; set; }
        public virtual DbSet<HittingStatsHeader> HittingStatsHeader { get; set; }
        public virtual DbSet<HittingStatsScoringPosition> HittingStatsScoringPosition { get; set; }
        public virtual DbSet<HittingStatsScoringPositionHeader> HittingStatsScoringPositionHeader { get; set; }
        public virtual DbSet<HittingStatsTeamDifference> HittingStatsTeamDifference { get; set; }
        public virtual DbSet<HittingStatsTeamDifferenceHeader> HittingStatsTeamDifferenceHeader { get; set; }
        public virtual DbSet<HittingStatsTeamDifferenceInfo> HittingStatsTeamDifferenceInfo { get; set; }
        public virtual DbSet<HomerunBest10> HomerunBest10 { get; set; }
        public virtual DbSet<HomerunBest10Header> HomerunBest10Header { get; set; }
        public virtual DbSet<HomerunInfoGL> HomerunInfoGL { get; set; }
        public virtual DbSet<HomerunInfoRGI> HomerunInfoRGI { get; set; }
        public virtual DbSet<InningScoreInfoCO> InningScoreInfoCO { get; set; }
        public virtual DbSet<LosePitcherGL> LosePitcherGL { get; set; }
        public virtual DbSet<LosingPitcherRGI> LosingPitcherRGI { get; set; }
        public virtual DbSet<ManagerInfoST> ManagerInfoST { get; set; }
        public virtual DbSet<MasterTransfersNpb> MasterTransfersNpb { get; set; }
        public virtual DbSet<MonthGroupSS> MonthGroupSS { get; set; }
        public virtual DbSet<MonthGroupSSN> MonthGroupSSN { get; set; }
        public virtual DbSet<NoteInfoGL> NoteInfoGL { get; set; }
        public virtual DbSet<OfficialStatsHeaderNpb> OfficialStatsHeaderNpb { get; set; }
        public virtual DbSet<OfficialStatsNpb> OfficialStatsNpb { get; set; }
        public virtual DbSet<PersonInfo> PersonInfo { get; set; }
        public virtual DbSet<PitcherGL> PitcherGL { get; set; }
        public virtual DbSet<PitcherInfoRGI> PitcherInfoRGI { get; set; }
        public virtual DbSet<PitchingStats> PitchingStats { get; set; }
        public virtual DbSet<PitchingStats3Years> PitchingStats3Years { get; set; }
        public virtual DbSet<PitchingStats3YearsInfo> PitchingStats3YearsInfo { get; set; }
        public virtual DbSet<PitchingStats3YearsTeams> PitchingStats3YearsTeams { get; set; }
        public virtual DbSet<PitchingStats6thGame> PitchingStats6thGame { get; set; }
        public virtual DbSet<PitchingStats6thGameHeader> PitchingStats6thGameHeader { get; set; }
        public virtual DbSet<PitchingStats6thGameInfo> PitchingStats6thGameInfo { get; set; }
        public virtual DbSet<PitchingStatsHeader> PitchingStatsHeader { get; set; }
        public virtual DbSet<PitchingStatsTeamsOpponent> PitchingStatsTeamsOpponent { get; set; }
        public virtual DbSet<PitchingStatsTeamsOpponentHeader> PitchingStatsTeamsOpponentHeader { get; set; }
        public virtual DbSet<PitchingStatsTeamsOpponentInfo> PitchingStatsTeamsOpponentInfo { get; set; }
        public virtual DbSet<PlayerGL> PlayerGL { get; set; }
        public virtual DbSet<PlayerInfoGO> PlayerInfoGO { get; set; }
        public virtual DbSet<PlayerInfoMST> PlayerInfoMST { get; set; }
        public virtual DbSet<PlayerInfoMSTHeader> PlayerInfoMSTHeader { get; set; }
        public virtual DbSet<PlayerInfoST> PlayerInfoST { get; set; }
        public virtual DbSet<RealGameInfoRootRGI> RealGameInfoRootRGI { get; set; }
        public virtual DbSet<ReliefInfoGL> ReliefInfoGL { get; set; }
        public virtual DbSet<RunBattedInBest10> RunBattedInBest10 { get; set; }
        public virtual DbSet<RunBattedInBest10Header> RunBattedInBest10Header { get; set; }
        public virtual DbSet<RunInfoRGI> RunInfoRGI { get; set; }
        public virtual DbSet<SaveBest10> SaveBest10 { get; set; }
        public virtual DbSet<SaveBest10Header> SaveBest10Header { get; set; }
        public virtual DbSet<SavePitcherGL> SavePitcherGL { get; set; }
        public virtual DbSet<SavingPitcherRGI> SavingPitcherRGI { get; set; }
        public virtual DbSet<ScoreGL> ScoreGL { get; set; }
        public virtual DbSet<ScoreGTE> ScoreGTE { get; set; }
        public virtual DbSet<ScoreGTS> ScoreGTS { get; set; }
        public virtual DbSet<ScoreInfoGL> ScoreInfoGL { get; set; }
        public virtual DbSet<ScoreRGI> ScoreRGI { get; set; }
        public virtual DbSet<SeasonScheduleSS> SeasonScheduleSS { get; set; }
        public virtual DbSet<StartingGameST> StartingGameST { get; set; }
        public virtual DbSet<TeamGL> TeamGL { get; set; }
        public virtual DbSet<TeamInfoCO> TeamInfoCO { get; set; }
        public virtual DbSet<TeamInfoGO> TeamInfoGO { get; set; }
        public virtual DbSet<TeamInfoGTE> TeamInfoGTE { get; set; }
        public virtual DbSet<TeamInfoGTS> TeamInfoGTS { get; set; }
        public virtual DbSet<TeamInfoMST> TeamInfoMST { get; set; }
        public virtual DbSet<TeamInfoPSP> TeamInfoPSP { get; set; }
        public virtual DbSet<TeamInfoST> TeamInfoST { get; set; }
        public virtual DbSet<TeamStats10thGame> TeamStats10thGame { get; set; }
        public virtual DbSet<TeamStats10thGameHeader> TeamStats10thGameHeader { get; set; }
        public virtual DbSet<TeamStatsCardDifference> TeamStatsCardDifference { get; set; }
        public virtual DbSet<TeamStatsCardDifferenceHeader> TeamStatsCardDifferenceHeader { get; set; }
        public virtual DbSet<TeamStatsCardDifferenceInfo> TeamStatsCardDifferenceInfo { get; set; }
        public virtual DbSet<TextGTE> TextGTE { get; set; }
        public virtual DbSet<TextGTS> TextGTS { get; set; }
        public virtual DbSet<TextInfoGTE> TextInfoGTE { get; set; }
        public virtual DbSet<TextInfoGTS> TextInfoGTS { get; set; }
        public virtual DbSet<UnpireInfoST> UnpireInfoST { get; set; }
        public virtual DbSet<VsPitcherGL> VsPitcherGL { get; set; }
        public virtual DbSet<WinBest10> WinBest10 { get; set; }
        public virtual DbSet<WinBest10Header> WinBest10Header { get; set; }
        public virtual DbSet<WinningPitcherRGI> WinningPitcherRGI { get; set; }
        public virtual DbSet<WinPitcherGL> WinPitcherGL { get; set; }
        public virtual DbSet<TeamIconNpb> TeamIconNpb { get; set; }
    }
}
