//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonInfo
    {
        public long PersonInfoId { get; set; }
        public long DirectoryId { get; set; }
        public int ID { get; set; }
        public short StaffKind { get; set; }
        public string StaffTitle { get; set; }
        public Nullable<short> PositionType { get; set; }
        public string BackNumber { get; set; }
        public string PlayerName { get; set; }
        public string PlayerNameK { get; set; }
        public string DelivName { get; set; }
        public string DelivFirstName { get; set; }
        public string DelivLastName { get; set; }
        public string DelivFirstNameK { get; set; }
        public string DelivLastNameK { get; set; }
        public Nullable<int> Birthday { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<short> PitchingArm { get; set; }
        public Nullable<short> BattingType { get; set; }
        public string Hometown { get; set; }
        public Nullable<int> Age { get; set; }
        public string Blood { get; set; }
        public string Career { get; set; }
        public Nullable<int> ProTotal { get; set; }
        public Nullable<int> DraftYear { get; set; }
        public string DraftNo { get; set; }
        public string Prize { get; set; }
        public string DSComment { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
