//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PitchingStatsTeamsOpponent
    {
        public long PitchingStatsTeamsOpponentId { get; set; }
        public long PitchingStatsTeamsOpponentHeaderId { get; set; }
        public int TeamCD { get; set; }
        public string ShortNameTeam { get; set; }
        public Nullable<int> PlayerCD { get; set; }
        public string Name { get; set; }
        public string ShortNamePlayer { get; set; }
        public string Num { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
