//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PitchingStats3YearsTeams
    {
        public long PitchingStats3YearsTeamsId { get; set; }
        public int TeamID { get; set; }
        public string Team { get; set; }
        public string TeamS { get; set; }
        public string TeamE { get; set; }
        public string TeamES { get; set; }
        public string TeamInitial { get; set; }
        public Nullable<int> SendDate { get; set; }
        public Nullable<int> PlayerC { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
