//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PitchingStats
    {
        public long PitchingStatsId { get; set; }
        public long PitchingStatsHeaderId { get; set; }
        public int TeamCD { get; set; }
        public string ShortNameTeam { get; set; }
        public Nullable<int> PlayerCD { get; set; }
        public string Name { get; set; }
        public string ShortNamePlayer { get; set; }
        public string Num { get; set; }
        public string EarnedRunAverage { get; set; }
        public Nullable<int> Game { get; set; }
        public Nullable<int> CompleteGame { get; set; }
        public Nullable<int> Finished { get; set; }
        public Nullable<int> Started { get; set; }
        public Nullable<int> Extension { get; set; }
        public Nullable<int> Shutout { get; set; }
        public Nullable<int> NoBaseOnBall { get; set; }
        public Nullable<int> Win { get; set; }
        public Nullable<int> Lost { get; set; }
        public Nullable<int> Save { get; set; }
        public Nullable<int> Hold { get; set; }
        public Nullable<int> HoldPoint { get; set; }
        public Nullable<int> Batmen { get; set; }
        public Nullable<int> InningsPitched { get; set; }
        public Nullable<int> InningsPitched3rd { get; set; }
        public Nullable<int> Hit { get; set; }
        public Nullable<int> HomeRunHitAgainst { get; set; }
        public Nullable<int> Strikeout { get; set; }
        public Nullable<int> BasesOnBall { get; set; }
        public Nullable<int> HitBastsmen { get; set; }
        public Nullable<int> WildPitch { get; set; }
        public Nullable<int> Balk { get; set; }
        public string WinningPercentage { get; set; }
        public string StrikeoutPercentage { get; set; }
        public Nullable<int> PointLost { get; set; }
        public Nullable<int> EarnedRun { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
