//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PitchingStats6thGameInfo
    {
        public long PitchingStats6thGameInfoId { get; set; }
        public long PitchingStats6thGameId { get; set; }
        public int TeamsOpponentCD { get; set; }
        public string ShortNameTeamsOpponent { get; set; }
        public Nullable<int> Round { get; set; }
        public Nullable<int> GameDate { get; set; }
        public Nullable<int> MoundCD { get; set; }
        public Nullable<int> MoundRankingCD { get; set; }
        public Nullable<int> PitchingResult { get; set; }
        public Nullable<int> Batmen { get; set; }
        public Nullable<int> InningsPitched { get; set; }
        public string InningsPitched3rd { get; set; }
        public Nullable<int> Hit { get; set; }
        public Nullable<int> HomeRunHitAgainst { get; set; }
        public Nullable<int> Strikeout { get; set; }
        public Nullable<int> BasesOnBall { get; set; }
        public Nullable<int> HitBastsmen { get; set; }
        public Nullable<int> WildPitch { get; set; }
        public Nullable<int> Balk { get; set; }
        public Nullable<int> TotalPitch { get; set; }
        public Nullable<int> PointLost { get; set; }
        public Nullable<int> EarnedRun { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
