//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerInfoGO
    {
        public long PlayerInfoGOId { get; set; }
        public long TeamInfoGOId { get; set; }
        public short BatNo { get; set; }
        public short Position { get; set; }
        public int PlayerID { get; set; }
        public string BackNumber { get; set; }
        public string PlayerNameS { get; set; }
        public string PlayerNameL { get; set; }
        public Nullable<short> PitchingArm { get; set; }
        public Nullable<short> BattingType { get; set; }
        public string Avg { get; set; }
        public Nullable<int> Hr { get; set; }
        public Nullable<int> Rbi { get; set; }
        public Nullable<short> Condition { get; set; }
        public Nullable<int> TeamID { get; set; }
        public string TeamS { get; set; }
        public string TeamES { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
