//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealGameInfoRootRGI
    {
        public long RealGameInfoRootRGIId { get; set; }
        public string FixedDistribute { get; set; }
        public string ControlNO { get; set; }
        public string Created { get; set; }
        public Nullable<int> GameAssortment { get; set; }
        public Nullable<int> Season { get; set; }
        public Nullable<int> Matchday { get; set; }
        public string GameCD { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
