//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RunInfoRGI
    {
        public long RunInfoRGIId { get; set; }
        public long ScoreRGIId { get; set; }
        public int Inning { get; set; }
        public Nullable<int> Run { get; set; }
        public Nullable<int> NothingInning { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
