//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreGL
    {
        public long ScoreGLId { get; set; }
        public long TeamGLId { get; set; }
        public int Inn { get; set; }
        public short TB { get; set; }
        public string R { get; set; }
        public Nullable<int> H { get; set; }
        public Nullable<int> BB { get; set; }
        public Nullable<int> ColCount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
