//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreRGI
    {
        public long ScoreRGIId { get; set; }
        public long RealGameInfoRootRGIId { get; set; }
        public string HomeVisitor { get; set; }
        public int TeamCD { get; set; }
        public string ShortNameTeam { get; set; }
        public Nullable<int> TotalScore { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
