//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeasonScheduleSS
    {
        public long SeasonScheduleSSId { get; set; }
        public int Year { get; set; }
        public int GameTypeID { get; set; }
        public string GameTypeName { get; set; }
        public Nullable<int> TotalGameC { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
