//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamInfoST
    {
        public long TeamInfoSTId { get; set; }
        public long StartingGameSTId { get; set; }
        public short HV { get; set; }
        public int TeamID { get; set; }
        public string TeamName { get; set; }
        public string TeamNameS { get; set; }
        public string TeamNameE { get; set; }
        public string TeamNameES { get; set; }
        public string TeamNameInitial { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
