//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamStatsCardDifferenceInfo
    {
        public long TeamStatsCardDifferenceInfoId { get; set; }
        public long TeamStatsCardDifferenceId { get; set; }
        public int AnotherLeagueF { get; set; }
        public int TeamsOpponentCD { get; set; }
        public string ShortNameTeamsOpponent { get; set; }
        public Nullable<int> Win { get; set; }
        public Nullable<int> Lose { get; set; }
        public Nullable<int> Draw { get; set; }
        public Nullable<int> Game { get; set; }
        public Nullable<int> Run { get; set; }
        public Nullable<int> PointLost { get; set; }
        public Nullable<int> Hit { get; set; }
        public Nullable<int> Homerun { get; set; }
        public Nullable<int> StrikeOut { get; set; }
        public Nullable<int> BaseOnBall { get; set; }
        public Nullable<int> HitByPitch { get; set; }
        public Nullable<int> DoublePlay { get; set; }
        public Nullable<int> StolenBase { get; set; }
        public Nullable<int> Error { get; set; }
        public string BattingAverage { get; set; }
        public string EarnedRunAverage { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
