//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamStats10thGame
    {
        public long TeamStats10thGameId { get; set; }
        public long TeamStats10thGameHeaderId { get; set; }
        public int GameDate { get; set; }
        public int TeamsOpponentCD { get; set; }
        public string ShortNameTeamsOpponent { get; set; }
        public Nullable<int> Round { get; set; }
        public Nullable<int> StadiumCD { get; set; }
        public string Stadium { get; set; }
        public string Score { get; set; }
        public string GameResult { get; set; }
        public Nullable<int> GamesStartedCD { get; set; }
        public string ShortNameGamesStart { get; set; }
        public string ResponsibilityPitcherCD { get; set; }
        public string ShortNameResponsibilityPitcher { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
