//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamInfoMST
    {
        public long TeamInfoMSTId { get; set; }
        public int TeamCD { get; set; }
        public Nullable<int> LocalID { get; set; }
        public string LocalName { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public string DistrictName { get; set; }
        public Nullable<int> LeagueID { get; set; }
        public string League { get; set; }
        public string LeagueK { get; set; }
        public string ShortNameLeague { get; set; }
        public string LeagueE { get; set; }
        public string LeagueES { get; set; }
        public string ShortNameTeam { get; set; }
        public string Team { get; set; }
        public string TeamK { get; set; }
        public string TeamE { get; set; }
        public string TeamES { get; set; }
        public string OnceNameTeam { get; set; }
        public Nullable<int> SmartStart { get; set; }
        public Nullable<int> SmartEnd { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
