//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamInfoGTS
    {
        public long TeamInfoGTSId { get; set; }
        public long GameInfoGTSId { get; set; }
        public short HV { get; set; }
        public int ID { get; set; }
        public string NameS { get; set; }
        public string NameES { get; set; }
        public Nullable<int> R { get; set; }
        public Nullable<int> H { get; set; }
        public Nullable<int> E { get; set; }
        public string Relief { get; set; }
        public string Homerun { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
