//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamGL
    {
        public long TeamGLId { get; set; }
        public long ScoreInfoGLId { get; set; }
        public short HV { get; set; }
        public int ID { get; set; }
        public string Name { get; set; }
        public string NameS { get; set; }
        public string NameE { get; set; }
        public string NameES { get; set; }
        public string NameInitial { get; set; }
        public Nullable<int> R { get; set; }
        public Nullable<int> PA { get; set; }
        public Nullable<int> H { get; set; }
        public Nullable<int> BB { get; set; }
        public Nullable<int> SB { get; set; }
        public Nullable<int> E { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
