//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Npb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnpireInfoST
    {
        public long UnpireInfoSTId { get; set; }
        public long StartingGameSTId { get; set; }
        public string Chief { get; set; }
        public string First { get; set; }
        public string Second { get; set; }
        public string Third { get; set; }
        public string Left { get; set; }
        public string Right { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
