//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Prize.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoodsSpec
    {
        public long GoodSpecId { get; set; }
        public string GoodName { get; set; }
        public string SubName { get; set; }
        public string ThumbnailUrl { get; set; }
        public string FullImageUrl { get; set; }
        public string Description { get; set; }
        public int PointsForBuy { get; set; }
        public int PointsForDraw { get; set; }
        public string CreatedAccountID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedAccountID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
