//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Prize.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RallyGoods
    {
        public long RallyGoodId { get; set; }
        public long RallyId { get; set; }
        public long GoodSpecId { get; set; }
        public short EntryMethod { get; set; }
        public short EntryLimit { get; set; }
        public int Points { get; set; }
        public int WinVolume { get; set; }
        public string CreatedAccountID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedAccountID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
