//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Prize.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rallies
    {
        public long RallyId { get; set; }
        public string RallyName { get; set; }
        public string ImageUrl { get; set; }
        public string Description { get; set; }
        public System.DateTime EntryStartDate { get; set; }
        public Nullable<System.DateTime> EntryEndDate { get; set; }
        public string CreatedAccountID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedAccountID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
