//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Mlb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyScheduleHeader
    {
        public long DailyScheduleHeaderId { get; set; }
        public string Created { get; set; }
        public Nullable<int> GameDate { get; set; }
        public Nullable<int> GameDateJPN { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
