//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Mlb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailySchedule
    {
        public long DailyScheduleId { get; set; }
        public long DailyScheduleHeaderId { get; set; }
        public int SeqNo { get; set; }
        public int SeasonID { get; set; }
        public int GameID { get; set; }
        public string Time { get; set; }
        public string StadiumName { get; set; }
        public Nullable<int> HomeTeamID { get; set; }
        public string HomeTeamFullName { get; set; }
        public string HomeTeamName { get; set; }
        public string HomeNoticeStarterName { get; set; }
        public string HomeNoticeStarterNum { get; set; }
        public Nullable<short> HomeNoticeStarterArm { get; set; }
        public Nullable<int> VisitorTeamID { get; set; }
        public string VisitorTeamFullName { get; set; }
        public string VisitorTeamName { get; set; }
        public string VisitorNoticeStarterName { get; set; }
        public string VisitorNoticeStarterNum { get; set; }
        public Nullable<short> VisitorNoticeStarterArm { get; set; }
        public Nullable<int> WinLast5 { get; set; }
        public Nullable<int> LoseLast5 { get; set; }
        public Nullable<int> GameCount { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
