//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Mlb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JapanesePlayers
    {
        public long JapanesePlayersId { get; set; }
        public long TeamInfoId { get; set; }
        public string PlayerName { get; set; }
        public string Years { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
