//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Mlb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeagueGroupMlb
    {
        public long LeagueGroupMlbId { get; set; }
        public long OfficialStatsHeaderMlbId { get; set; }
        public int LeagueID { get; set; }
        public string LeagueName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
