//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Mlb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterTransfersMlb
    {
        public int Id { get; set; }
        public string No { get; set; }
        public string FunctionName { get; set; }
        public string FileName { get; set; }
        public string FilePathServer { get; set; }
        public string Schema { get; set; }
        public string SuffixTables { get; set; }
        public string IgnoreTables { get; set; }
        public string QuerySqlDelete { get; set; }
        public Nullable<short> HasCustomHeader { get; set; }
        public Nullable<short> HasSubFolder { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
