//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Mlb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MlbEntities : DbContext
    {
        public MlbEntities()
            : base("name=MlbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DailySchedule> DailySchedule { get; set; }
        public virtual DbSet<DailyScheduleHeader> DailyScheduleHeader { get; set; }
        public virtual DbSet<DayGroup> DayGroup { get; set; }
        public virtual DbSet<DivGroupMlb> DivGroupMlb { get; set; }
        public virtual DbSet<JapanesePlayers> JapanesePlayers { get; set; }
        public virtual DbSet<LeagueGroupMlb> LeagueGroupMlb { get; set; }
        public virtual DbSet<MasterTransfersMlb> MasterTransfersMlb { get; set; }
        public virtual DbSet<MonthGroup> MonthGroup { get; set; }
        public virtual DbSet<OfficialStatsHeaderMlb> OfficialStatsHeaderMlb { get; set; }
        public virtual DbSet<OfficialStatsMlb> OfficialStatsMlb { get; set; }
        public virtual DbSet<RealGameInfo> RealGameInfo { get; set; }
        public virtual DbSet<RealGameInfoHeader> RealGameInfoHeader { get; set; }
        public virtual DbSet<SeasonSchedule> SeasonSchedule { get; set; }
        public virtual DbSet<SeasonScheduleHeader> SeasonScheduleHeader { get; set; }
        public virtual DbSet<StatLast5Years> StatLast5Years { get; set; }
        public virtual DbSet<TeamIconMlb> TeamIconMlb { get; set; }
        public virtual DbSet<TeamInfo> TeamInfo { get; set; }
        public virtual DbSet<TeamInfoMSTHeader> TeamInfoMSTHeader { get; set; }
    }
}
