//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Mlb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficialStatsMlb
    {
        public long OfficialStatsMlbId { get; set; }
        public long DivGroupMlbId { get; set; }
        public int Ranking { get; set; }
        public int TeamID { get; set; }
        public string TeamFullName { get; set; }
        public string TeamName { get; set; }
        public Nullable<int> GameCount { get; set; }
        public Nullable<int> Win { get; set; }
        public Nullable<int> Lose { get; set; }
        public string WinningPercentage { get; set; }
        public string GameBehind { get; set; }
        public Nullable<int> Run { get; set; }
        public Nullable<int> PointLost { get; set; }
        public Nullable<int> Homerun { get; set; }
        public Nullable<int> StolenBase { get; set; }
        public string BattingAverage { get; set; }
        public string EarnedRunAverage { get; set; }
        public Nullable<int> RunsBattingIn { get; set; }
        public Nullable<int> WinLast10 { get; set; }
        public Nullable<int> LoseLast10 { get; set; }
        public string Streak { get; set; }
        public string StatHome { get; set; }
        public string StatVisitor { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
