//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Mlb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealGameInfo
    {
        public long RealGameInfoId { get; set; }
        public long RealGameInfoHeaderId { get; set; }
        public int SeqNo { get; set; }
        public int GameID { get; set; }
        public Nullable<int> HomeTeamID { get; set; }
        public string HomeTeamFullName { get; set; }
        public string HomeTeamName { get; set; }
        public string HomeStarterName { get; set; }
        public string HomeStarterNum { get; set; }
        public Nullable<short> HomeStarterArm { get; set; }
        public Nullable<int> HomeScore { get; set; }
        public Nullable<int> HomeHits { get; set; }
        public Nullable<int> HomeErrors { get; set; }
        public Nullable<int> VisitorTeamID { get; set; }
        public string VisitorTeamFullName { get; set; }
        public string VisitorTeamName { get; set; }
        public string VisitorStarterName { get; set; }
        public string VisitorStarterNum { get; set; }
        public Nullable<short> VisitorStarterArm { get; set; }
        public Nullable<int> VisitorScore { get; set; }
        public Nullable<int> VisitorHits { get; set; }
        public Nullable<int> VisitorErrors { get; set; }
        public Nullable<int> GameStateID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
