//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Areas.Mlb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeasonSchedule
    {
        public long SeasonScheduleId { get; set; }
        public long DayGroupId { get; set; }
        public int SeqNo { get; set; }
        public int SeasonID { get; set; }
        public int GameID { get; set; }
        public string Time { get; set; }
        public string StadiumName { get; set; }
        public Nullable<int> HomeTeamID { get; set; }
        public string HomeTeamFullName { get; set; }
        public string HomeTeamName { get; set; }
        public Nullable<int> VisitorTeamID { get; set; }
        public string VisitorTeamFullName { get; set; }
        public string VisitorTeamName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
