//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppActionLog
    {
        public long Id { get; set; }
        public Nullable<long> MemberId { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string UserAgent { get; set; }
        public string Url { get; set; }
        public string UrlReferrer { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string SessionId { get; set; }
    }
}
