//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackOfficeAccount
    {
        public string AccountId { get; set; }
        public string Password { get; set; }
        public short PasswordExpireDate { get; set; }
        public System.DateTime PasswordLastUpdateTime { get; set; }
        public string Mail { get; set; }
        public short Status { get; set; }
        public string CreatedAccountId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedAccountID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
