//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BriefNews
    {
        public long NewsItemID { get; set; }
        public string DateFolderName { get; set; }
        public string Filename { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public System.DateTime CarryLimitDate { get; set; }
        public int RevisionID { get; set; }
        public string Update { get; set; }
        public string Status { get; set; }
        public string Headline { get; set; }
        public string SubHeadline { get; set; }
        public string newstext { get; set; }
        public string SentFrom { get; set; }
        public string CreatedAccountID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedAccountID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
