//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComEntities : DbContext
    {
        public ComEntities()
            : base("name=ComEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BriefNews> BriefNews { get; set; }
        public virtual DbSet<CampaignInfo> CampaignInfo { get; set; }
        public virtual DbSet<Contribution> Contribution { get; set; }
        public virtual DbSet<ContributionQuotOrg> ContributionQuotOrg { get; set; }
        public virtual DbSet<CurrentDayPerExpectTargetTotalPoint> CurrentDayPerExpectTargetTotalPoint { get; set; }
        public virtual DbSet<Deviation> Deviation { get; set; }
        public virtual DbSet<EntryHistory> EntryHistory { get; set; }
        public virtual DbSet<ExpectTarget> ExpectTarget { get; set; }
        public virtual DbSet<FollowList> FollowList { get; set; }
        public virtual DbSet<GroupMember> GroupMember { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<ItpcSubject> ItpcSubject { get; set; }
        public virtual DbSet<ItpcSubjectMaster> ItpcSubjectMaster { get; set; }
        public virtual DbSet<LikeSports> LikeSports { get; set; }
        public virtual DbSet<LikeTeam> LikeTeam { get; set; }
        public virtual DbSet<LoginHistory> LoginHistory { get; set; }
        public virtual DbSet<MailDeliverCond> MailDeliverCond { get; set; }
        public virtual DbSet<MonthlyResults> MonthlyResults { get; set; }
        public virtual DbSet<NewsGenre> NewsGenre { get; set; }
        public virtual DbSet<NewsGenreMaster> NewsGenreMaster { get; set; }
        public virtual DbSet<NewsHistory> NewsHistory { get; set; }
        public virtual DbSet<NoticeInfo> NoticeInfo { get; set; }
        public virtual DbSet<PageInfo> PageInfo { get; set; }
        public virtual DbSet<PhotoNews> PhotoNews { get; set; }
        public virtual DbSet<PointHistory> PointHistory { get; set; }
        public virtual DbSet<PointRanking> PointRanking { get; set; }
        public virtual DbSet<PopularTopicsAggregate> PopularTopicsAggregate { get; set; }
        public virtual DbSet<PrefectureMaster> PrefectureMaster { get; set; }
        public virtual DbSet<Prize> Prize { get; set; }
        public virtual DbSet<QuotTopic> QuotTopic { get; set; }
        public virtual DbSet<SeasonTotalResults> SeasonTotalResults { get; set; }
        public virtual DbSet<SNSShareHistory> SNSShareHistory { get; set; }
        public virtual DbSet<SportsMaster> SportsMaster { get; set; }
        public virtual DbSet<SystemParamater> SystemParamater { get; set; }
        public virtual DbSet<TokenAcInfo> TokenAcInfo { get; set; }
        public virtual DbSet<TokenControl> TokenControl { get; set; }
        public virtual DbSet<TotalDailyReport> TotalDailyReport { get; set; }
        public virtual DbSet<TotalMemberReport> TotalMemberReport { get; set; }
        public virtual DbSet<TotalMonthlyReport> TotalMonthlyReport { get; set; }
        public virtual DbSet<TotalWeeklyReport> TotalWeeklyReport { get; set; }
        public virtual DbSet<WeekResults> WeekResults { get; set; }
        public virtual DbSet<SportsStandardDeviation> SportsStandardDeviation { get; set; }
        public virtual DbSet<BetClassMaster> BetClassMaster { get; set; }
        public virtual DbSet<BackOfficeAccount> BackOfficeAccount { get; set; }
        public virtual DbSet<ExpectPoint> ExpectPoint { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<NewsReading> NewsReading { get; set; }
        public virtual DbSet<NewsTopic> NewsTopic { get; set; }
        public virtual DbSet<TopicMaster> TopicMaster { get; set; }
        public virtual DbSet<OddsInfo> OddsInfo { get; set; }
        public virtual DbSet<PayOffPoints> PayOffPoints { get; set; }
        public virtual DbSet<Point> Point { get; set; }
        public virtual DbSet<NewsClassMaster> NewsClassMaster { get; set; }
        public virtual DbSet<BetSelectMaster> BetSelectMaster { get; set; }
        public virtual DbSet<MailDeliverCondMaster> MailDeliverCondMaster { get; set; }
        public virtual DbSet<SnsCorpInformation> SnsCorpInformation { get; set; }
        public virtual DbSet<NewsReadingSumView> NewsReadingSumView { get; set; }
        public virtual DbSet<ContributionReading> ContributionReading { get; set; }
        public virtual DbSet<SnsAuthInformation> SnsAuthInformation { get; set; }
        public virtual DbSet<NoticeDeliverySubject> NoticeDeliverySubject { get; set; }
        public virtual DbSet<PointBulkTemporal> PointBulkTemporal { get; set; }
        public virtual DbSet<UnitBrowser> UnitBrowser { get; set; }
        public virtual DbSet<PossesionPointRanking> PossesionPointRanking { get; set; }
        public virtual DbSet<AppActionLog> AppActionLog { get; set; }
        public virtual DbSet<NoticePopupDisplayHistory> NoticePopupDisplayHistory { get; set; }
    }
}
