//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContributionQuotOrg
    {
        public long ContributeId { get; set; }
        public long NewsClassId { get; set; }
        public long QuoteUniqueId1 { get; set; }
        public long QuoteUniqueId2 { get; set; }
        public long QuoteUniqueId3 { get; set; }
        public short Status { get; set; }
    }
}
