//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deviation
    {
        public int StartYear { get; set; }
        public int Month { get; set; }
        public short Week { get; set; }
        public int SportsID { get; set; }
        public int UniqueID { get; set; }
        public short ClassClass { get; set; }
        public decimal ExpectationsDeviation { get; set; }
        public decimal BetrayalDeviation { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
