//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpectTarget
    {
        public long ExpectTargetID { get; set; }
        public int SportsID { get; set; }
        public short ClassClass { get; set; }
        public int UniqueID { get; set; }
        public short Status { get; set; }
        public Nullable<System.DateTime> StartScheduleDate { get; set; }
        public Nullable<int> FixBetSelectID { get; set; }
        public Nullable<System.DateTime> FixDate { get; set; }
        public string CreatedAccountID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedAccountID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
