//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpectPoint
    {
        public long ExpectPointID { get; set; }
        public long ExpectTargetID { get; set; }
        public long PointID { get; set; }
        public int ExpectPoint1 { get; set; }
        public Nullable<int> AcquisitionPoint { get; set; }
        public Nullable<short> ClassClass { get; set; }
        public Nullable<int> UniqueID { get; set; }
        public Nullable<int> BetSelectID { get; set; }
        public Nullable<short> VorD { get; set; }
        public short SituationStatus { get; set; }
        public string CreatedAccountID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedAccountID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
