//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItpcSubjectMaster
    {
        public int IptcSubjectCode { get; set; }
        public int Subject { get; set; }
        public Nullable<int> SubjectMatter { get; set; }
        public Nullable<int> SubjectDetail { get; set; }
        public string SubjectJp { get; set; }
        public string SubjectMatterJp { get; set; }
        public string SubjectDetailJp { get; set; }
        public string CreatedAccountID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedAccountID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
