//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public long MemberId { get; set; }
        public string DisplayMemberId { get; set; }
        public string Nickname { get; set; }
        public string ProfileImg { get; set; }
        public Nullable<short> Gender { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<short> BirthdayYear { get; set; }
        public Nullable<short> BirthdayMonth { get; set; }
        public Nullable<short> BirthdayDay { get; set; }
        public Nullable<short> PrefecturesId { get; set; }
        public string Mail { get; set; }
        public string Password { get; set; }
        public short Status { get; set; }
        public Nullable<bool> LoginKeepFlg { get; set; }
        public Nullable<System.DateTime> InterimRegistTime { get; set; }
        public Nullable<System.DateTime> RegistTime { get; set; }
        public Nullable<System.DateTime> ExitTime { get; set; }
        public Nullable<System.DateTime> CompelExitTime { get; set; }
        public string CreatedAccountID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedAccountID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
