//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoticeInfo
    {
        public long NoticeId { get; set; }
        public short NoticeClass { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public System.DateTime DeliveryTime { get; set; }
        public System.DateTime NoticeDisplayEndTime { get; set; }
        public string TransitionsURL { get; set; }
        public string MailCC { get; set; }
        public string MailBCC { get; set; }
        public Nullable<short> MailSendStatus { get; set; }
        public string CreatedAccountID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedAccountID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public short MailDelivCondID { get; set; }
        public string NoticeBody { get; set; }
    }
}
