//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayOffPoints
    {
        public long PayOffPointsId { get; set; }
        public long MemberId { get; set; }
        public int PayOffPoints1 { get; set; }
        public int EntryPoints { get; set; }
        public int EntryEnablePoints { get; set; }
        public Nullable<System.DateTime> PayOffFinishTime { get; set; }
        public Nullable<System.DateTime> EntryStartTime { get; set; }
        public Nullable<System.DateTime> EntryEndTime { get; set; }
    }
}
