//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PopularTopicsAggregate
    {
        public System.DateTime TargetDate { get; set; }
        public long TopicID { get; set; }
        public long NewsClassID { get; set; }
        public long Views { get; set; }
    }
}
