//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prize
    {
        public long PrizeID { get; set; }
        public string PrizeName { get; set; }
        public string PrizeImg { get; set; }
        public string PrizeDescription { get; set; }
        public int PrizePoints { get; set; }
        public short PrizeMethod { get; set; }
        public System.DateTime EntryStartTime { get; set; }
        public System.DateTime EntryEndTime { get; set; }
        public string CreatedAccountID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedAccountID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
