//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeasonTotalResults
    {
        public short StartYear { get; set; }
        public int SportsID { get; set; }
        public long MemberID { get; set; }
        public int ExpectNumber { get; set; }
        public short CorrectPercent { get; set; }
        public int CorrectPoint { get; set; }
        public Nullable<System.DateTime> LastTotalDate { get; set; }
    }
}
