//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportsStandardDeviation
    {
        public long StartYear { get; set; }
        public int SportsID { get; set; }
        public short ClassClass { get; set; }
        public decimal ExpectationsAverage { get; set; }
        public decimal ExpectationsVariance { get; set; }
        public decimal ExpectationsStandardDeviation { get; set; }
        public decimal BetrayalAverage { get; set; }
        public decimal BetrayalVariance { get; set; }
        public decimal BetrayalStandardDeviation { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
