//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalMemberReport
    {
        public int TotalTargetTime { get; set; }
        public short SportsId { get; set; }
        public short TotalTargetYear { get; set; }
        public short TotalTargetMonth { get; set; }
        public short TotalTargetDay { get; set; }
        public short TotalTargetWeek { get; set; }
        public short MemberCount { get; set; }
        public short ExitCount { get; set; }
        public int GroundTotalMember { get; set; }
    }
}
