//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalWeeklyReport
    {
        public short SportsId { get; set; }
        public short TotalTargetYear { get; set; }
        public short TotalTargetMonth { get; set; }
        public short TotalTargetWeek { get; set; }
        public short GameCount { get; set; }
        public int ExpectCount { get; set; }
        public int FirstExpectCount { get; set; }
        public int ContinueExpectCount { get; set; }
        public int PerExpectCount { get; set; }
        public short UuExpectCount { get; set; }
        public int WriteCount { get; set; }
        public int WriteUuCount { get; set; }
        public int UuWriteCount { get; set; }
        public int GroundTotalWirte { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
