//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Splg.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitBrowser
    {
        public long UnitBrowserId { get; set; }
        public string BrowserID { get; set; }
        public string BrowserType { get; set; }
        public string CookieGuid { get; set; }
        public string UserAgent { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
